---
  - name: restart varnish
    become: yes
    service:
        name: varnish
        state: restarted

  - name: restart varnishncsa
    become: yes
    service:
        name: varnishncsa
        state: restarted
