---
  - name: Drush | Install required packages
    apt: name={{ item }} state=present
    with_items:
      - curl
    sudo: yes

  - name: Drush | Install Composer
    shell: >
      curl -sS https://getcomposer.org/installer | php
      creates=/usr/local/bin/composer

  - name: Drush | Move Composer into globally-accessible location
    shell: >
      mv composer.phar /usr/local/bin/composer
      creates=/usr/local/bin/composer

  - name: Drush | Clone Drush from GitHub
    git: >
      repo=https://github.com/drush-ops/drush.git
      dest=/usr/local/share/drush
      version=7.x

  - name: Drush | Install Drush dependencies with Composer
    shell: >
      /usr/local/bin/composer install --prefer-source --no-interaction
      chdir=/usr/local/share/drush
      creates=/usr/local/share/drush/vendor/autoload.php

  - name: Drush | Create drush symlink
    file: >
      src=/usr/local/share/drush/drush
      dest=/usr/local/bin/drush
      state=link

  - name: Drush | Run drush to finish setting it up
    command: "/usr/local/bin/drush"
    register: drush_result
    changed_when: "'Execute a drush command' not in drush_result.stdout"

  - name: Drush | Clone DSLM from drupal.org
    git: >
        repo=http://git.drupal.org/project/dslm.git
        dest=/usr/local/share/drush/commands/dslm
        version=7.x-2.x

  - name: Drush | Add DSLM_BASE variable to .profile
    lineinfile:
      dest=/home/dplagnt/.profile
      line="export DSLM_BASE=/data/code/dslm_base"
      regexp="^export DSLM_BASE=/data/code/dslm_base"
      state=present
      insertafter=EOF
      create=True

  - name: Drush | Add PACKAGES_BASE variable to .profile
    lineinfile:
      dest=/home/dplagnt/.profile
      line="export PACKAGES_BASE=/data/code/packages_base"
      regexp="^export PACKAGES_BASE=/data/code/packages_base"
      state=present
      insertafter=EOF
      create=True

  - name: Drush | Create ~/.drush
    file: >
      path=/home/dplagnt/.drush
      state=directory
      owner=dplagnt

  - name: Drush | Install Drush-patchfile with Composer
    shell: >
      /usr/local/bin/composer require davereid/drush-patchfile:dev-master
      chdir=/home/dplagnt/.drush
      creates=/home/dplagnt/.drush/composer.json

  - file: path=/home/dplagnt/.drush owner=dplagnt group=lapurd state=directory recurse=yes

  - name: Drush | Copy drushrc.php to VM
    template:
      src: drushrc.php.j2
      dest: /home/dplagnt/.drush/drushrc.php
      owner: dplagnt
