---
  - name:  Install necessary packages
    yum: name={{ item }} state=present update_cache=yes
    with_items:
      - httpd-2.2.15

  - name: Ensure Apache (httpd) is started and enabled on boot.
    service: name=httpd state=started enabled=yes

  - name:  Add virtual host configuration
    template: src=express.conf.j2 dest=/etc/httpd/conf.d/express.conf mode=0650 owner=apache group=apache

  - name:  Check that our config is valid
    command: apachectl configtest
    register: result
    ignore_errors: True

  - name:  Bad Config - Ending playbook
    fail: msg="Configuration file is not valid. Please check that before re-running the playbook."
    when: result|failed

  - name:  Push ports configuration
    template: src=ports.conf.j2 dest=/etc/httpd/conf/ports.conf mode=0640 owner=root group=root
    notify:
      - restart apache

  - name:  Create directory to store outgoing mail.
    file: >
        path=~/var/log/mail
        state=directory
        mode=777

  - name:  Create directory to store outgoing mail.
    file: dest=/var/log/mail mode=777 owner=root state=directory

  - name:  Copy sendmail php code to server
    copy: src=sendmail dest=/usr/local/bin/sendmail owner=root group=root mode=0755

  - name:  Add sendmail lines to cli php.ini
    lineinfile:
      dest=/etc/php5/cli/php.ini
      line="sendmail_path = /usr/local/bin/sendmail"
      regexp="^sendmail_path = /usr/local/bin/sendmail"
      state=present
      insertafter=EOF
      create=True

  - name:  Add sendmail lines to apache php.ini
    lineinfile:
      dest=/etc/php5/apache2/php.ini
      line='sendmail_path = /usr/local/bin/sendmail'
      regexp='^sendmail_path = /usr/local/bin/sendmail'
      state=present
      insertafter=EOF
      create=True
    notify:
      - restart apache
