---
  - name: Get rid of default Varnish files
    when: express_code_varnish
    file:
        path: "{{ item }}"
        state: absent
    with_items:
        - /etc/varnish/default.vcl

  - name: Symlink in default.vcl
    when: express_code_varnish
    file:
        src: "/data/code/varnish/default.vcl"
        dest: "/etc/varnish/default.vcl"
        state: link
    notify:
        - restart varnish

  - name: Get rid of ELK files
    when: express_code_elk
    file:
        path: "{{ item }}"
        state: absent
    with_items:
        - /etc/elasticsearch/elasticsearch.yml
        - /etc/elasticsearch/logging.yml
        - /etc/logstash/conf.d

  - name: Symlink in our ELK configuration
    when: express_code_elk
    file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
    with_items:
        - { src: "/data/code/elasticsearch_config/elasticsearch.yml", dest: "/etc/elasticsearch/elasticsearch.yml"}
        - { src: "/data/code/elasticsearch_config/logging.yml", dest: "/etc/elasticsearch/logging.yml"}
        - { src: "/data/code/logstash/conf.d", dest: "/etc/logstash/conf.d"}
    notify:
        - restart elasticsearch
        - restart logstash

    - name: Remove logstash output
      when: express_code_logstash
      file:
          path: "{{ item }}"
          state: absent
      with_items:
        - /etc/logstash/conf.d/90-output-indicies.conf

    - name: Add localized logstash output
      when: express_code_logstash
      template:
          src: "logstash-90-output-indicies.conf.j2"
          dest: "/etc/logstash/conf.d/90-output-indicies.conf"
          owner: "root"
          group: "root"
          mode: 0644
          force: yes
      notify: restart logstash

    - name: Remove logstash_shipper output
      when: express_code_logstash_shipper
      file:
          path: "{{ item }}"
          state: absent
      with_items:
        - /etc/logstash/conf.d/90-output-redis.conf

    - name: Add localized logstash_shipper output
      when: express_code_logstash_shipper
      template:
          src: "logstash-90-output-redis.conf.j2"
          dest: "/etc/logstash/conf.d/90-output-redis.conf"
          owner: "root"
          group: "root"
          mode: 0644
          force: yes
      notify: restart logstash
