---
  - name: Express code | Create initial directory structure
    file: path={{ item }} state=directory
    with_items:
      - /data/web/custom
      - /data/web/express
      - /data/web/homepage
      - /data/releases
      - /data/code
      - /data/files


  - name: Express code | Clone dslm_base repository
    git:
      repo=git@github.com:CuBoulder/dslm_base.git
      dest=~/data/code/dslm_base
      version=poolb-dev
      recursive=yes
      accept_hostkey=yes

  - name: Express code | Clone package_base repository
    git:
      repo=git@github.com:CuBoulder/packages_base.git
      dest=~/data/code/packages_base
      version=dev
      recursive=yes
      accept_hostkey=yes
