---
  - name: Install memcached
    yum: pkg={{ item }} state=installed update_cache=yes
    with_items:
     - memcached
     - libmemcached
     - zlib-devel

  # Configure Memcached.
  - name: Copy Memcached configuration.
    template:
      src: memcached.conf.j2
      dest: /etc/sysconfig/memcached
      owner: root
      group: root
      mode: 0644
    notify: restart memcached

  - name: Install PECL memcache
    shell: yes | pecl install memcache
    register: pecl_memcache_result
    ignore_errors: True

  - name:  Bad Configuration - Ending playbook
    fail: "msg={{ pecl_memcache_result.stdout}}"
    when: pecl_memcache_result.stdout.find('failed') == -1 and pecl_memcache_result.stdout.find('already installed and is the same as the released version') == -1

  - name: Ensure Memcached is started and set to run on startup.
    service: name=memcached state=started enabled=yes
