---
  - name: Install memcached
    yum: pkg={{ item }} state=installed update_cache=yes
    with_items:
     - memcached
     - libmemcached
     - zlib-devel
    sudo: true

  - name: Install PECL memcache
    shell: yes | pecl install memcache creates=/usr/lib/php5/20090626+lfs/memcache.so
    sudo: true
    register: pecl_memcache_result
    ignore_errors: True

  - name:  Bad Config - Ending playbook
    fail: msg="{{ pecl_memcache_result.stdout}}"
    when: "pecl_memcache_result.stdout.find('failed') == -1 and pecl_memcache_result.stdout.find('already installed and is the same as the released version') == -1"

  - name: Add memcache lines to apache php.ini
    lineinfile:
      dest=/etc/php5/apache2/php.ini
      line="extension=memcache.so"
      regexp="^extension=memcache.so"
      state=present
      insertafter=EOF
      create=True
    notify:
      - restart apache
      - restart memcache

  - name: Add memcache lines to apache php.ini
    lineinfile:
      dest=/etc/php5/apache2/php.ini
      line='memcache.hash_strategy="consistent"'
      regexp='^memcache.hash_strategy="consistent"'
      state=present
      insertafter=EOF
      create=True
    notify:
      - restart apache
      - restart memcache

  - name: Add memcache lines to cli php.ini
    lineinfile:
      dest=/etc/php5/cli/php.ini
      line="extension=memcache.so"
      regexp="^extension=memcache.so"
      state=present
      insertafter=EOF
      create=True
    notify:
      - restart memcache

  - name: Add memcache lines to cli php.ini
    lineinfile:
      dest=/etc/php5/cli/php.ini
      line='memcache.hash_strategy="consistent"'
      regexp='^memcache.hash_strategy="consistent"'
      state=present
      insertafter=EOF
      create=True
    notify:
      - restart memcache
