---
  - name: Installs necessary OS packages
    yum: pkg={{ item }} state=latest
    with_items:
      - openssl
      - python-pip
      - python-devel
      - gcc
      - gcc-c++
      - libffi-devel
      - openldap
      - cyrus-sasl-lib
      - mongodb


  - name: Install Python packages
    pip: name={{ item.name }} version={{ item.version }}
    with_items:
      - { name: 'requests', version: '2.7.0' }
      - { name: 'flask', version: '0.10.1' }
      - { name: 'jinja2', version: '2.7.3' }
      - { name: 'fabric', version: '1.8.0' }
      - { name: 'pymongo', version: '2.8.1' }
      - { name: 'cerberus', version: '0.9.1' }
      - { name: 'events', version: '0.2.1' }
      #- { name: 'pycrypto', version: '2.6.1' }
      - { name: 'pyopenssl', version: '0.15.1' }
      - { name: 'paramiko', version: '1.12.0'}
      - { name: 'eve', version: '0.5.3' }
      - { name: 'celery', version: '3.1.12' }


  - name: Push celeryd init script
    copy: src=celeryd dest=/etc/init.d/ mode=0777 owner=root group=root

  - name: Push celerybeat init script
    copy: src=celerybeat dest=/etc/init.d/ mode=0777

  - name: Pushes celeryd configuration
    template: src=celeryd.j2 dest=/etc/default/celeryd mode=0640 owner=root group=root

  - name: Create celery group
    group: name=celery state=present

  - name: Create celery user
    user: name=celery group=celery

  - name: Update user vagrant groups
    user: name=vagrant groups=celery append=yes
