---
  - name: Install php packages
    yum: pkg={{ item }} state=present update_cache=yes
    with_items:
     - php-pecl-apc
    sudo: true
    notify:
      - restart apache

  - name: Create APC config file
    template:
      src: apc.ini.j2
      dest: /etc/php5/apache2/apc.ini
      owner: root
      group: root
      force: yes
      mode: 0644
    notify:
      - restart apache
