---
  # This playbook will be run on webservers for the Inventory.

  # Need to set up ssh first
  - include: ../utilities/push_ssh_keys.yml

  - hosts: inventory
    sudo: yes
    roles:
      - ../../roles/server_base
      - ../../roles/python
      # - logstash_forwarder
