---
  - name:  Install necessary packages
    yum: name={{ item }} state=present update_cache=yes
    with_items:
      - httpd-2.2.15
      - mod_ssl
      - openssl

  - name: Ensure Apache (httpd) is started and enabled on boot.
    service: name=httpd state=started enabled=yes
