---
- hosts: inventory

  tasks:
    - name: Remove old key file
      become: yes
      become_user: dplagnt
      file:
          path: ".ssh/id_rsa_deploy"
          state: absent

    - name: Remove old key pub file
      become: yes
      become_user: dplagnt
      file:
          path: ".ssh/id_rsa_deploy.pub"
          state: absent

    - name: Create ssh key for dplagnt to deploy with
      become: yes
      become_user: dplagnt
      user:
          name: dplagnt
          generate_ssh_key: yes
          ssh_key_file: .ssh/id_rsa_deploy

    - name: Fetch key
      become: yes
      become_user: dplagnt
      fetch:
          src: "/home/dplagnt/.ssh/id_rsa_deploy.pub"
          dest: "/tmp/id_rsa_deploy.pub"
          fail_on_missing: yes
          flat: yes
