---
- hosts: deploy_targets

  tasks:
    - name: Copy ssh key to express.local
      become: yes
      become_user: dplagnt
      copy:
          src: "/tmp/id_rsa_deploy.pub"
          dest: "/tmp/"
          mode: 0600

    - name: Add key to authorized_keys
      become: yes
      become_user: dplagnt
      authorized_key:
          user: dplagnt
          key: "{{ lookup('file', '/tmp/id_rsa_deploy.pub') }}"
