---
- hosts: express.local
  vars_prompt:
    - name: "type"
      prompt: "[C]reate an new site or [R]einstall an existing site"
      private: no

    - name: "profile"
      prompt: "Which profile would you like to use? [E]xpress or [F]it"
      private: no

    - name: "path"
      prompt: "Enter the path for the site"
      private: no

  vars:
      database: "express_{{path}}"

  tasks:
      - name: Create mysql database.
        mysql_db:
            name: "{{database}}"
            state: present
        when: type == "C" or type == "c" or type == "create" or type == "Create"

      - name: Clear drush cache
        action: command drush cc drush
        when: type == "C" or type == "c" or type == "create" or type == "Create"
        args:
            chdir: "/data/web/express/"

      - name: Create dslm entry for site
        become: yes
        become_user: dplagnt
        command: "drush dslm-new {{path}} --current"
        when: type == "C" or type == "c" or type == "create" or type == "Create"
        args:
            chdir: "/data/web/express/"
            creates: "/data/web/express/{{path}}/install.php"

      - name: Add CU Fit
        become: yes
        become_user: dplagnt
        command: drush dslm-add-profile cu_fit --current
        when: (type == "C" or type == "c" or type == "create" or type == "Create") and (profile == "F" or profile == "f" or profile == "fit" or profile == "Fit" or profile == "FIT")
        args:
            chdir: "/data/web/express/{{path}}/"
            creates: "/data/web/express/{{path}}/profiles/cu_fit/cu_fit.info"

      - name: Add Express
        become: yes
        become_user: dplagnt
        command: drush dslm-add-profile express --current
        when: (type == "C" or type == "c" or type == "create" or type == "Create") and (profile == "E" or profile == "e" or profile == "express" or profile == "Express")
        args:
            chdir: "/data/web/express/{{path}}/"
            creates: "/data/web/express/{{path}}/profiles/express/express.info"

      - name: Set file permissions
        become: yes
        when: type == "C" or type == "c" or type == "create" or type == "Create"
        file:
            path: "/data/web/express/{{path}}"
            state: directory
            mode: 0775
            recurse: yes

      - name: Create settings.php file for Fit.
        when: (type == "C" or type == "c" or type == "create" or type == "Create") and (profile == "F" or profile == "f" or profile == "fit" or profile == "Fit" or profile == "FIT")
        template:
            src: templates/express_settings.j2
            dest: "/data/web/express/{{path}}/sites/default/settings.php"
            mode: 0774

      - name: Create settings.php file for Express.
        when: (type == "C" or type == "c" or type == "create" or type == "Create") and (profile == "E" or profile == "e" or profile == "express" or profile == "Express")
        template:
            src: templates/express_settings.express.j2
            dest: "/data/web/express/{{path}}/sites/default/settings.php"
            mode: 0774

      - name: Create settings.local_pre.php file.
        when: type == "C" or type == "c" or type == "create" or type == "Create"
        template:
            src: templates/express_settings_local_pre.j2
            dest: "/data/web/express/{{path}}/sites/default/settings.local_pre.php"
            mode: 0774

      - name: Create settings.local_post.php file.
        when: type == "C" or type == "c" or type == "create" or type == "Create"
        template:
            src: templates/express_settings_local_post.j2
            dest: "/data/web/express/{{path}}/sites/default/settings.local_post.php"
            mode: 0774

      - name: Create temp files directory
        when: type == "C" or type == "c" or type == "create" or type == "Create"
        file:
            path: "{{ item }}"
            state: directory
        with_items:
            - "/data/files/{{path}}/tmp"

      - name: Remove files directory
        when: type == "R" or type == "r" or type == "reinstall" or type == "Reinstall"
        file:
            path: "{{ item }}"
            state: absent
        with_items:
            - "/data/files/{{path}}/files"

      - name: Install site with Fit.
        when: profile == "F" or profile == "f" or profile == "fit" or profile == "Fit" or profile == "FIT"
        command: drush si cu_fit -y
        become: yes
        become_user: dplagnt
        register: install_output
        args:
            chdir: "/data/web/express/{{path}}/"

      - name: Install site with Express.
        when: profile == "E" or profile == "e" or profile == "express" or profile == "Express"
        command: drush si express -y
        become: yes
        become_user: dplagnt
        register: install_output
        args:
            chdir: "/data/web/express/{{path}}/"

      - debug: var=install_output.stdout_lines
