---
- hosts: express.local
  vars_prompt:
    - name: "path"
      prompt: "Enter the path of the site you would like to test. Leave blank for"
      private: no
      default: "testing"

    - name: "bundles"
      prompt: "Enter the machine name(s) of the bundles you would like to enable (comma seperated). Leave blank for"
      private: no
      default: "express"

    - name: "tags"
      prompt: "Enter an argument for the 'tags' parameter. Comma seperated list => OR, && => AND, ~ => NOT. Leave blank for"
      private: no
      default: "all"

    - name: "install"
      prompt: "Do you want to do a clean install of the site first? (Y/N)"
      private: no

  tasks:

    - name: Install site
      when: install == "y" or install == "Y" or install == "Yes"
      command: drush si express -y
      become: yes
      become_user: dplagnt
      register: install_output
      args:
          chdir: "/data/web/express/{{path}}/"

    - name: Enable bundles
      when: bundles != "express"
      command: "drush en {{ bundles | join(' ') }} -y"
      become: yes
      become_user: dplagnt
      register: enable_output
      args:
          chdir: "/data/web/express/{{path}}/"


    - name: Start Selenium Server
      command: xvfb-run -a java -jar /var/selenium2/selenium-server-standalone-2.46.0.jar
      async: 45
      poll: 0
      become: yes

    - name: Run script
      become: yes
      script: roles/behat/scripts/behat_params.sh
      environment:
        BEHAT_TESTING_PATH: "{{ path }}"

    - name: Run the tests - All tests
      become: yes
      command: "behat --suite={{bundles}}"
      register: behat
      args:
          chdir: "/data/web/express/{{path}}"
      when: tags == "all"



    - name: Run the tests - Some tests
      command: "behat --tags {{tags}} --suite={{bundles}}"
      become: yes
      register: behat
      args:
          chdir: "/data/web/express/{{path}}/profiles/express/tests/behat"
      when: tags != "all"
      environment:
        BEHAT_TESTING_PATH: "{{ path }}"

    - debug: var=behat.stdout_lines
