- hosts: 127.0.0.1

  vars_prompt:
    - name: "force"
      prompt: "Would you like to force a complete rebuild? [Y/N] This will destory any local modifications to any associated repositories."
      private: no

  connection: local

  tasks:
    - name: Reset repositories
      when: force == "Y" or force == "y" or force == "Yes" or force == "yes"
      command: "git reset --hard origin/{{ item.branch }}"
      args:
        chdir: "{{ item.path }}"
      with_items:
          - { path: "~/denexpress_local/data/code/dslm_base", branch: "poolb-dev"}
          - { path: "~/denexpress_local/data/code/packages_base", branch: "dev"}
          - { path: "~/denexpress_local/data/code/varnish", branch: "master"}
          - { path: "~/denexpress_local/data/code/inventory", branch: "dev"}
          - { path: "~/denexpress_local/data/code/logstash", branch: "master"}


    - name: Reset submodules
      when: force == "Y" or force == "y" or force == "Yes" or force == "yes"
      command: "git submodule update --init"
      args:
          chdir: "{{ item }}"
      with_items:
          - "~/denexpress_local/data/code/dslm_base"
          - "~/denexpress_local/data/code/packages_base"

    - name: Fetch the repositories
      command: "git fetch"
      args:
          chdir: "{{ item.path }}"
      with_items:
          - { path: "~/denexpress_local/data/code/dslm_base"}
          - { path: "~/denexpress_local/data/code/packages_base"}
          - { path: "~/denexpress_local/data/code/varnish"}
          - { path: "~/denexpress_local/data/code/inventory"}
          - { path: "~/denexpress_local/data/code/logstash"}
          - { path: "~/denexpress_local/data/code/dslm_base/profiles/express-current"}

    - name: Checkout the correct branches
      command: "git checkout {{ item.branch }}"
      args:
          chdir: "{{ item.path }}"
      with_items:
          - { path: "~/denexpress_local/data/code/dslm_base", branch: "poolb-dev"}
          - { path: "~/denexpress_local/data/code/packages_base", branch: "dev"}
          - { path: "~/denexpress_local/data/code/varnish", branch: "master"}
          - { path: "~/denexpress_local/data/code/inventory", branch: "dev"}
          - { path: "~/denexpress_local/data/code/logstash", branch: "master"}
          - { path: "~/denexpress_local/data/code/dslm_base/profiles/express-current", branch: "dev"}

    - name: Pull the repositories
      command: "git pull"
      args:
          chdir: "{{ item.path }}"
      with_items:
          - { path: "~/denexpress_local/data/code/dslm_base"}
          - { path: "~/denexpress_local/data/code/packages_base"}
          - { path: "~/denexpress_local/data/code/varnish"}
          - { path: "~/denexpress_local/data/code/inventory"}
          - { path: "~/denexpress_local/data/code/logstash"}
          - { path: "~/denexpress_local/data/code/dslm_base/profiles/express-current"}
