---
  # This playbook will be run on webservers for Express.

  # Need to set up ssh first
  - hosts: web
    sudo: yes

    tasks:
      # This should work too / #2372
      # - name: Pushes user key to root's on vagrant boxes
      #   action: authorized_key key=$FILE($item) user=root
      #   first_available_file:
      #     - ~/.ssh/id_dsa.pub
      #     - ~/.ssh/id_rsa.pub

      - name: Install necessary OS packages
        yum: name={{ item }} state=present
        with_items:
          - libselinux-python

      - name: Creates destination directory
        # Workaround for #2372
        file: state=directory mode=0700 dest=/root/.ssh/

      - name: Pushes user's rsa key to root's vagrant box (it's ok if this TASK fails)
        # action: authorized_key user=root key='$FILE(~/.ssh/id_rsa.pub)'
        # Workaround for #2372
        copy: src=~/.ssh/id_rsa.pub dest=/root/.ssh/authorized_keys owner=root mode=0600
        register: rsa
        ignore_errors: yes

      - name: Pushes user's dsa key to root's vagrant box (it's NOT ok if both TASKs fail)
        # action: authorized_key user=root key='$FILE(~/.ssh/id_dsa.pub)'
        # Workaround for #2372
        copy: src=~/.ssh/id_dsa.pub dest=/root/.ssh/authorized_keys owner=root mode=0600
        when: rsa|failed

  # Now we install all the applications we need to run Express
  # Drush includes the Composer install, so needs to be before Behat.
  - hosts: web
    sudo: yes
    roles:
      - server_base
      - apache
      - php
      - mysql
      - varnish
      - apc
      - memcache
      - xdebug
      - rvm
      - drush
      - behat
      # - include: ../tasks/logstash_forwarder.yml
      - express_code
