---
  # This playbook will be run on webservers for Express.

  # Need to set up ssh first
  - include: push_ssh_keys.yml

  # Now we install all the applications we need to run Express
  # Drush includes the Composer install, so needs to be before Behat.
  - hosts: web
    become: yes
    # Pick which configuration files we want to swap in
    vars:
        express_code_varnish: true
        express_code_elk: false
        express_code_logstash: false
        express_code_logstash_shipper: true
    roles:
        - server_base
        - apache
        - php
        - mysql
        - varnish
        - apc
        - memcache
        - xdebug
        - rvm
        - drush
        - behat
        - logstash
        - express_code
        - logging
