---
  # This playbook will be run on webservers for the Inventory.

  # Need to set up ssh first
  - include: push_ssh_keys.yml

  - hosts: inventory
    become: yes
    vars:
        express_code_varnish: false
        express_code_elk: false
        express_code_logstash: false
        express_code_logstash_shipper: true
    roles:
      - server_base
      - apache_inventory
      - python
      - logstash
    vars:
      python_location: /home/dplagnt/inventory-python27-environment

  - include: dplagnt_ssh_key_src.yml
