---
  # This playbook will be run on webservers for the Inventory.

  # Need to set up ssh first
  - include: push_ssh_keys.yml

  - hosts: inventory
    become: yes
    vars:
        express_code_varnish: false
        express_code_elk: false
    roles:
        - server_base
        - python
        # - logstash_forwarder
