---
  # This playbook will be run on webservers for the Inventory.

  # Need to set up ssh first
  - include: push_ssh_keys.yml

  - hosts: inventory
    become: yes
    roles:
      - server_base
      - apache_inventory
      - python
      # - logstash_forwarder
    vars:
      python_location: /home/dplagnt/inventory-python27-environment
