---
- name: Xdebug |  Install Xdebug PHP component
  apt: pkg=php5-xdebug state=installed
  register: xdebug_installed
  tags: xdebug
  sudo: true

- name: Copy xdebug INI into php.d folder.
  template:
    src: xdebug.ini.j2
    dest: /etc/php5/conf.d/xdebug.ini
    owner: root
    group: root
    mode: 0644
  notify: restart apache
